name: 'Setup Project Workspace'
description: 'Sets up the workspace for the project'

inputs:
  repository:
    description: 'Name of the repository to checkout'
    required: false
    default: ''
  ref:
    description: Branch, tag or SHA to checkout
    required: false
    default: ''
  token:
    description: 'Personal access token to checkout multiple repositories'
    required: false
    default: ''
  path:
   description: "Relative path to place the repository"
   required: false
   default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout the target branch
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository  == '' && github.repository || inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token  == '' && github.token || inputs.token }}
        path: ${{ inputs.path }}

