name: "Maven Install"
description: >
    Action to install Java and Maven
inputs:
  distribution:
    description: "Java Distribution"
    required: false
    default: "corretto"
  java-version:
    description: "Java version to use"
    required: false
    default: "17"
  cache:
     description: "Cache to use"
     required: false
     default: "maven"

runs:
  using: composite
  steps:
     -  name: Set up Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 #v4.2.1
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.cache }}

     -  name: check maven version
        run: bash
        shell: |
            echo Maven version is "$(mvn -v)"


