name: Commitlint on CI

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0

      - name: Update apt and fix broken packages
        run: |
          sudo apt update
          sudo apt --fix-broken install -y

      - name: Set up node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version

      - name: Install commitlint
        run: |
          npm install -g conventional-changelog-conventionalcommits
          npm install -g commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
