name: njsscan workflow

on:
  workflow_call:

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning

    steps:
      - name: Checking out workspace
        uses: jeeshan12/resusable_workflows/.github/actions/setup/workspace@v2.5.2

      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@d58d8b2f26322cd35a9efb8003baac517f226d81 #v7.0.0
        with:
          args: ". --sarif --output njsscan-results.sarif || true"
        continue-on-error: true

      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@956f09c2ef1926b580554b9014cfb8a51abf89dd #v2.16.6
        with:
          sarif_file: njsscan-results.sarif
