name: Release Tags

on:
  workflow_dispatch:

jobs:
  release:
    name: Release Github tags
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Install Node.js
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn cache clean

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
