name: Run Selenium Tests on Headless chrome

on:
  workflow_call:
    inputs:
     fileName:
        required: true
        type: string

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: browser-actions/setup-chrome@v1
      id: setup-chrome
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Run with Maven
      run: mvn test -Dfile=${{inputs.fileName}} -Dheadless=true
    - name: Archive Test Results 
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: ./target/surefire-reports
