name: SonarCloud

on:
  workflow_call:
    secrets:
      sonar-token:
        description: Sonar token to scan the repo
        required: true

    inputs:
      distribution:
        required: false
        type: string
        default: "corretto"

      java-version:
        required: false
        type: string
        default: "21"

      cache:
        required: false
        type: string
        default: "maven"

      repository-name:
        type: string
        required: true

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out workspace
        uses: jeeshan12/resusable_workflows/.github/actions/setup/workspace@v2.4.0

      - name: Setting up Maven and Java
        uses: jeeshan12/resusable_workflows/.github/actions/setup/maven@feat-sonarcloud-workflow
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.cache }}

      - name: Cache SonarCloud packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven dependencies
        uses: jeeshan12/resusable_workflows/.github/actions/cache/maven@v2.5.0
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Build and analyze code
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.repository-name }} -DskipTests
